Repository mapbox/mapbox-events-android, pull requests merged in 2018-11, with the labels that each got.

#265 Fix TelemetryService and applicationContext issue
  app/src/androidTest/java/com/mapbox/android/events/testapp/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/mapbox/android/events/testapp/MapboxTelemetryActivityTest.java
  gradle/dependencies.gradle
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryLocationEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: bug

#272 Fix crash due to null context reference in LocationBroadcastReceiver
  libtelemetry/src/main/java/com/mapbox/android/telemetry/BluetoothAudioType.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/HeadphonesAudioType.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationMapper.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapClickEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapDragendEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapEventFactory.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapLoadEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationState.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationUtils.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/SpeakerAudioType.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationEventTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationMapperTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientLocationEventTest.java
Labels: ready for review

#279 Integrate jacoco plugin with events repo
  app/build.gradle
  gradle/jacoco.gradle
  libcore/build.gradle
  liblocation/build.gradle
  libtelemetry/build.gradle
Labels: ready for review

#278 Record binary size
  .circleci/config.yml
  package.json
  scripts/check_binary_size.js
  scripts/metrics.sh
Labels: enhancement

#267 Update AlarmManager flag
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/AlarmReceiverInstrumentationTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/AlarmReceiverTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/AlarmSchedulerFlusherTest.java
Labels: bug

#285 Add codecov.yml
  codecov.yml
Labels: ready for review

#286 Add new CI user template
  ci.template
Labels: ready for review

#284 3.5.4 Changelog
  CHANGELOG.md
Labels: release

#288 Push mobile metrics to loading dock
  .circleci/config.yml
  ci.template
  cloudformation/ci.template.js
  package.json
  scripts/check_binary_size.sh
  scripts/metrics.sh
  scripts/publish_to_aws.sh
  scripts/publish_to_sizechecker.js
Labels: ready for review

#293 Publish metrics to AWS on master and release only
  .circleci/config.yml
  scripts/capture_binary_size_for_aws.sh
  scripts/check_binary_size.sh
Labels: ready for review

#290 Refactor listener management infrastructure & background mode support
  liblocation/build.gradle
  liblocation/src/androidTest/java/com/mapbox/android/core/location/LocationEngineInstrumentedTest.java
  liblocation/src/main/java/com/mapbox/android/core/location/AbstractLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/BackgroundLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/BroadcastReceiverProxy.java
  liblocation/src/main/java/com/mapbox/android/core/location/ForegroundLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/IntentHandler.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProxy.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationUpdatesBroadcastReceiverProxy.java
  liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/Utils.java
  liblocation/src/test/java/com/mapbox/android/core/location/AbstractLocationEngineImplTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/AndroidLocationEngineImplTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/GoogleLocationEngineImplTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineProviderTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineProxyTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineResultTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImplTest.java
Labels: enhancement, ready for review

#292 Add Vision UserAgent
  app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
Labels: bug

#254 Add lifecycle methods to track lifecycle of parent activity
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: bug

#297 Add UserAgent header to Config Request
  libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificateBlacklist.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/CertificateBlacklistTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: bug

#301 4.1.0 Telemetry + 1.1.0 Core Release
  CHANGELOG.md
  libcore/gradle.properties
  libtelemetry/gradle.properties
Labels: release
