Repository mapbox/mapbox-events-android, pull requests merged in 2018-09, with the labels that each got.

#205 Attachment Event
  libtelemetry/src/main/java/com/mapbox/android/telemetry/Attachment.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AttachmentListener.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AttachmentMetadata.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/FileAttachment.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/FileData.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionEventFactory.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
Labels: ready for review, spec change

#212 Change fieldIds to fileIds
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AttachmentListener.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
Labels: high priority, ready for review

#151 New Hashes and Blacklist
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificateBlacklist.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificatePinnerFactory.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/ChinaCertificatePins.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/ComCertificatePins.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClient.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientFactory.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientFactoryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
Labels: enhancement, high priority, ready for review

#214 3.2.0 Telemetry Release
  CHANGELOG.md
  libtelemetry/gradle.properties
Labels: release

#215 Update MOCK LocationEngine Type to REPLAY
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Labels: ready for review

#216 Re-add MOCK LocationEngine Type
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Labels: ready for review

#209 Detect BinderProxy
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Labels: bug, high priority, ready for review

#160 Schema Tests
  Makefile
  gradle/download-schema.gradle
  libtelemetry/.gitignore
  libtelemetry/build.gradle
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AppUserTurnstile.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/FeedbackEventData.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/FeedbackEventDataSerializer.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapDragendEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadataSerializer.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/NavigationEventFactoryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
Labels: ready for review, test

#217 More specific Proguard rules
  libcore/proguard-consumer.pro
Labels: ready for review

#221 StopTelemetryService obtainBoundInstances bug fix
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: bug

#224 3.2.1 Telemetry Release
  CHANGELOG.md
Labels: release
