Repository mapbox/mapbox-events-android, pull requests merged in 2018-05, with the labels that each got.

#133 Add new China Certificate Hashes
  libtelemetry/src/main/java/com/mapbox/android/telemetry/ChinaCertificatePins.java
Labels: enhancement

#136 Bug Fix for attempting to unbind a service that is already unregistered
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: bug

#139 Close Okhttp Response
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: bug

#154 3.1.2 Release
  CHANGELOG.md
Labels: release

#155 Make location event constructor package private
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
Labels: enhancement, ready for review
