Repository mapbox/mapbox-events-android, pull requests merged in 2018-03, with the labels that each got.

#72 Update OkHttp version to 3.10.0
  gradle/dependencies.gradle
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MockWebServerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientTest.java
Labels: bug, ready for review

#73 Remove System.out call from MapboxTelemetry
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: ready for review

#79 Fix overwritten alarms issue
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/AlarmReceiverInstrumentationTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/AlarmSchedulerFlusherTest.java
Labels: bug, ready for review

#81 Update Proguard rules
  app/src/main/res/layout/activity_main.xml
  libcore/build.gradle
  libcore/proguard-rules.pro
  liblocation/build.gradle
  liblocation/proguard-rules.pro
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LostLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LostLocationEngineFactory.java
  liblocation/src/main/java/com/mapbox/android/core/location/MockLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/UpdateLostRequestPriority.java
  libtelemetry/build.gradle
Labels: bug, ready for review

#83 Bring back the Mock location engine type
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Labels: bug, ready for review

#84 Remove Lost tail work
  gradle/dependencies.gradle
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/test/java/com/mapbox/android/telemetry/NavigationEventFactoryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SerializerTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientNavigationEventsTest.java
Labels: ready for review

#77 Disable Tag
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
Labels: enhancement, ready for review

#80 Fix duplicate location data issue
  gradle/dependencies.gradle
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/EventReceiverInstrumentationTest.java
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/EventReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/EventSender.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryLocationEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationReceiverTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
Labels: bug, ready for review

#91 Meta-Data Tag Optional
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryEnabler.java
Labels: RELEASE BLOCKING, bug, ready for review

#92 Incorrect UserAgent
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Labels: RELEASE BLOCKING, bug, ready for review

#96 Fix Circle-Ci not Downloading Dependencies
  .circleci/config.yml
Labels: bug

#98 Fix crash when sticky service is recreated
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Labels: RELEASE BLOCKING, bug, ready for review
