Repository mapbox/mapbox-events-android, pull requests merged in 2018-10, with the labels that each got.

#226 Fix FileAttachment Queue Bug
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: bug, ready for review

#227 ACCESS_FINE_LOCATION permission exception
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Labels: enhancement, ready for review

#233 3.3.0 Telemetry Release
  CHANGELOG.md
  libtelemetry/gradle.properties
Labels: release

#229 Location API refactor
  build.gradle
  build.sh
  gradle/dependencies.gradle
  libcore/build.gradle
  libcore/src/main/AndroidManifest.xml
  libcore/src/main/java/com/mapbox/android/core/connectivity/ConnectivityReceiver.java
  liblocation/build.gradle
  liblocation/src/androidTest/java/com/mapbox/android/core/location/ExampleInstrumentedTest.java
  liblocation/src/androidTest/java/com/mapbox/android/core/location/LocationEngineInstrumentedTest.java
  liblocation/src/main/AndroidManifest.xml
  liblocation/src/main/java/com/mapbox/android/core/location/AbstractLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineFactory.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/BackgroundLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/BroadcastReceiverProxy.java
  liblocation/src/main/java/com/mapbox/android/core/location/ClasspathChecker.java
  liblocation/src/main/java/com/mapbox/android/core/location/ForegroundLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineFactory.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/IntentHandler.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineCallback.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineListener.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEnginePriority.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineSupplier.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationUpdatesBroadcastReceiverProxy.java
  liblocation/src/main/java/com/mapbox/android/core/location/UpdateAndroidProvider.java
  liblocation/src/main/java/com/mapbox/android/core/location/UpdateGoogleRequestPriority.java
  liblocation/src/main/java/com/mapbox/android/core/location/Utils.java
  liblocation/src/test/java/com/mapbox/android/core/location/AbstractLocationEngineImplTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/ExampleUnitTest.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineTest.java
  libtelemetry/build.gradle
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
  test.sh
Labels: enhancement, high priority, ready for review

#235 Update Load Event with sdkIdentifier and sdkVersion
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapLoadEvent.java
Labels: enhancement

#237 Update dependencies and cleanup gradle scripts
  .circleci/config.yml
  app/build.gradle
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  libcore/build.gradle
  libcore/javadoc.gradle
  liblocation/build.gradle
  libtelemetry/build.gradle
  libtelemetry/javadoc.gradle
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: ready for review

#236 Telemetry SDK background location updates + batch locations
  app/build.gradle
  liblocation/src/main/java/com/mapbox/android/core/location/LocationUpdatesBroadcastReceiverProxy.java
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/LocationReceiverTest.java
Labels: ready for review

#241 PermissionChecker NPE
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryService.java
Labels: bug

#245 Add support for Vision object detection event (v2)
  libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionEventFactory.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionObjectDetectionEvent.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/SchemaTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
Labels: ready for review

#247 Mapbox Fused Location Engine
  build.gradle
  libcore/build.gradle
  liblocation/build.gradle
  liblocation/src/androidTest/java/com/mapbox/android/core/location/LocationEngineInstrumentedTest.java
  liblocation/src/main/java/com/mapbox/android/core/location/AbstractLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/ForegroundLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
  liblocation/src/main/java/com/mapbox/android/core/location/MapboxFusedLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/Utils.java
  liblocation/src/test/java/com/mapbox/android/core/location/LocationEngineTest.java
Labels: ready for review

#257 Handle potential 'null' last location returned by fused client
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngineImpl.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
Labels: ready for review

#260 4.0.0 Telemetry + 1.0.0 Core Release
  CHANGELOG.md
  libcore/gradle.properties
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineRequest.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineResult.java
  libtelemetry/gradle.properties
Labels: release
