Repository mapbox/mapbox-events-android, pull requests merged in 2018-04, with the labels that each got.

#100 Location Engine Singleton Bug
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngineProvider.java
Labels: RELEASE BLOCKING, bug, ready for review

#105 Remove unnecessary audio type setter from navigation metadata
  libtelemetry/src/main/java/com/mapbox/android/telemetry/NavigationMetadata.java
Labels: enhancement, ready for review

#106 Expose obtain universal unique identifier method publicly
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
Labels: enhancement, ready for review

#108 Generate user id from feedback event data internally
  libtelemetry/src/main/java/com/mapbox/android/telemetry/FeedbackEventData.java
Labels: enhancement, ready for review

#109 Fix Proguard issues
  .circleci/config.yml
  app/build.gradle
  app/proguard-rules.pro
  libcore/build.gradle
  libcore/proguard-consumer.pro
  libcore/proguard-rules.pro
  liblocation/build.gradle
  liblocation/proguard-rules.pro
  libtelemetry/build.gradle
  libtelemetry/proguard-consumer.pro
  libtelemetry/proguard-rules.pro
Labels: ready for review

#110 Add Alarm unregistering safe check
  libtelemetry/src/main/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
Labels: ready for review

#111 FastestInterval Documentation Update
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Labels: ready for review, spec change

#113 3.0.0 Release
  CHANGELOG.md
Labels: ready for review

#114 AndroidLocationEngine javadoc format change
  liblocation/src/main/java/com/mapbox/android/core/location/LocationEngine.java
Labels: ready for review

#115 Graph Dependencies
  .circleci/config.yml
  Makefile
  gradle/dependencies-graph.gradle
  gradle/dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  libcore/.gitignore
  libcore/build.gradle
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
  liblocation/src/main/java/com/mapbox/android/core/location/GoogleLocationEngine.java
  libtelemetry/.gitignore
  libtelemetry/build.gradle
Labels: ready for review

#117 Add service running check
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: bug, ready for review

#75 Location Job Service
  app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
  liblocation/src/main/java/com/mapbox/android/core/location/AndroidLocationEngine.java
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationJobService.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: enhancement, in progress

#126 Remove unnecessary update telemetry state from enable and disable methods
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetry.java
Labels: ready for review

#130 JobScheduler Context Bug
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationJobService.java
Labels: bug
