Repository mapbox/mapbox-events-android, pull requests merged in 2019-01, with the labels that each got.

#320 4.2.0 Release
  CHANGELOG.md
  libtelemetry/gradle.properties
Labels: release

#324 Prepare the repository as Maps SDK vendor
  .circleci/config.yml
  build.gradle
  gradle/dependencies.gradle
  libcore/build.gradle
  liblocation/build.gradle
  libtelemetry/build.gradle
Labels: ready for review

#331 Remove Unused Lifecycle Dependencies
  libtelemetry/build.gradle
Labels: spec change

#327 Additional Testing Around Blacklist and ConfigurationClient
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/CertificateBlacklistInstrumentationTests.java
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/ConfigurationClientInstrumentationTest.java
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificateBlacklist.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/ConfigurationClient.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/ConfigurationClientTest.java
Labels: ready for review, test

#328 Telemetry SDK Lite
  .circleci/config.yml
  app/build.gradle
  app/src/androidTest/java/com/mapbox/android/events/testapp/MapboxTelemetryActivityTest.java
  gradle/jacoco.gradle
  libtelemetry/build.gradle
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmMangerInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/AlarmReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/EventReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/TelemetryReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/AlarmSchedulerFlusher.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/EventReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/EventSender.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/JobSchedulerFlusher.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/PermissionCheckRunnable.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/SchedulerFlusherFactory.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/SchedulerFlusherJobService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/lite/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryClientSettings.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/VisionObjectDetectionEvent.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/AlarmReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/AlarmSchedulerFlusherTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/ConcurrentQueueTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/EventReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/EventsQueueTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/FullQueueFlusherTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/LocationEventTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/LocationMapperTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/LocationReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MockedFullQueueFlusher.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/TelemetryReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
Labels: ready for review
