Repository mapbox/mapbox-events-android, pull requests merged in 2019-03, with the labels that each got.

#349 Location collector refactor
  app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineController.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationMapper.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesJobIntentService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/SessionIdentifier.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/LocationEvent.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/SessionIdentifier.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/LocationMapperTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationEngineControllerImplTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiverTest.java
Labels: ready for review

#351 Sunset telemetry service
  gradle/dependencies.gradle
  libtelemetry/build.gradle
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/LocationReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/TelemetryReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/TelemetryServiceTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/LocationReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/PermissionCheckRunnable.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/TelemetryService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineController.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationEngineControllerImpl.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationMapper.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesJobIntentService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/main/java/com/mapbox/android/telemetry/ExponentialBackoff.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetryConstants.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryReceiver.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/AppUserTurnstileTest.java
  libtelemetry/src/test/java/com/mapbox/android/telemetry/ConfigurationClientTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/LocationReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapEventFactoryTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/TelemetryClientMapEventsTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/TelemetryReceiverTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/VisionEventFactoryTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationEngineControllerImplTest.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiverTest.java
  libtelemetry/src/testFull/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: ready for review

#354 Release Core 1.2.0
  CHANGELOG.md
  libcore/gradle.properties
Labels: release

#347 Add strict mode
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/android/events/testapp/MainActivity.java
  app/src/main/java/com/mapbox/android/events/testapp/MainAppInitProvider.java
  app/src/main/java/com/mapbox/android/events/testapp/MainApplication.java
  app/src/main/res/layout/activity_main.xml
  gradle/dependencies.gradle
  libtelemetry/src/androidTest/java/com/mapbox/android/telemetry/CertificateBlacklistInstrumentationTests.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/lite/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/main/AndroidManifest.xml
  libtelemetry/src/main/java/com/mapbox/android/telemetry/CertificateBlacklist.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/EventCallback.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryLocationEnabler.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/TelemetryUtils.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: ready for review

#363 Mismatched Dependency Issue
  gradle/dependencies.gradle
  libtelemetry/build.gradle
Labels: bug

#358 Resolve strict mode UntaggedSocketViolation issue
  libtelemetry/src/main/java/com/mapbox/android/telemetry/GzipRequestInterceptor.java
Labels: ready for review

#368 4.3.0 Release
  CHANGELOG.md
  libtelemetry/gradle.properties
Labels: release

#369 Fix unstable test cases in LocationCollectionClientInstrumentedTest
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
Labels: ready for review

#361 Crash reporter telemetry integration
  libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/FileUtilsInstrumentedTest.java
  libcore/src/androidTest/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderInstrumentationTest.java
  libcore/src/main/java/com/mapbox/android/core/FileUtils.java
  libcore/src/main/java/com/mapbox/android/core/crashreporter/CrashReportBuilder.java
  libcore/src/main/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlder.java
  libcore/src/test/java/com/mapbox/android/core/crashreporter/MapboxUncaughtExceptionHanlderTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/crash/CrashReporterClientInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/crash/CrashReporterJobIntentServiceInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/crash/TokenChangeBroadcastReceiverInstrumentationTest.java
  libtelemetry/src/androidTestFull/java/com/mapbox/android/telemetry/location/LocationCollectionClientInstrumentedTest.java
  libtelemetry/src/full/AndroidManifest.xml
  libtelemetry/src/full/java/com/mapbox/android/telemetry/CrashEvent.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/MapboxTelemetry.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/crash/CrashReporterClient.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/crash/CrashReporterJobIntentService.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/crash/TokenChangeBroadcastReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationCollectionClient.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/location/LocationUpdatesBroadcastReceiver.java
  libtelemetry/src/full/java/com/mapbox/android/telemetry/provider/MapboxTelemetryInitProvider.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/Event.java
  libtelemetry/src/main/java/com/mapbox/android/telemetry/MapboxTelemetryConstants.java
  libtelemetry/src/testFull/java/com/mapbox/android/telemetry/MapboxTelemetryTest.java
Labels: ready for review
